### ISSUE TITLE
Have you considered merging this into rubygems?

### ISSUE THREAD

**Issue by bf4** [brianstorti/rubygems_plugin_generator#1]

**Comment by brianstorti** [comment]
Well, I have a [pull request](https://github.com/rubygems/guides/pull/124) adding it to the plugins list, but I haven't considered merging this into rubygems.
I think the rubygems maintainers already have a lot on their plate to take care, I'd like to be responsible to maintain this generator and this can be harder if it's merged into rubygems.
I'll think more about it and maybe ask the rubygems maintainers if they think this is a good idea.

Thank you for the suggestion.

**Comment by bf4** [comment]
I merged it. @drbrain @evanphx would you consider having a rubygems' plugin generator merged into rubygems?  Seems reasonable to me, and not too much overhead.

**Comment by drbrain** [comment]
The dependency on thor would need to be replaced as RubyGems does not depend on libraries outside the standard library.

This gem is also very new. Despite it's simplicity I would rather see it mature under @brianstorti's maintainership for some time before importing it.

When merged it will take longer to add features as RubyGems' release cycle is slow, which will be frustrating to both contributors and @brianstorti.

**Comment by bf4** [comment]
So, not yet :)

**Comment by brianstorti** [comment]
Thanks for you input @bf4 and @drbrain.
When the time comes, I'd be happy to do the necessary changes to have it merged into RubyGems.
